/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./cjs/index.cjs]{@link ./cjs/index.cjs}
 * 
 **/
export const findIp  = function ()
{
    try
    {

        return true;
    }
    catch (e)
    {
        console.error(e);
    }

    return false;
};


