/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./test/unit-test.specs.cjs]{@link ./test/unit-test.specs.cjs}
 * 
 **/
import {expect}  from "chai";
/**
 * To generate tests for ESM:
 * $> npm run build:test
 */




import {getIps, getIpList, findIp} from "../esm/index.mjs";
 


describe("On esm/index.esm", () =>
{
    describe("The function getIps", () =>
    {
        it("should return an ip", async () =>
        {
            const ips = getIps();
            expect(Object.keys(ips).length).to.be.greaterThan(0);
        });
    });

    describe("The function getIpList", () =>
    {
        it("should return a list of ips", async () =>
        {
            const ips = getIpList();
            expect(ips.length).to.be.greaterThan(0);
        });
    });

    describe("The function getLocalIp", () =>
    {
        it("should return an ip", async () =>
        {
            const localIp = findIp();
            expect(localIp).to.match(/\d+\.\d+\.\d+\.\d+/);
        });
    });

});